# Generated by Django 4.2.7 on 2024-01-16 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('produits', '0003_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='categories.categorie'),
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
    ]
